### ISSUE TITLE
Recursive variable definition

### ISSUE THREAD

**Issue by stevenvachon** [seven-phases-max/less-plugin-lists#3] opened 2016-08-16 20:09 UTC
``` less
@list: .class1, .class2;
@list: cat(@list, .class3);
```

throws

**Comment by seven-phases-max** [comment] 2016-09-20 19:57
Expected, since recursive variable definition is not allowed in Less (because of the [lazy evaluation](http://lesscss.org/features/#variables-feature-lazy-loading)). It's the same ill-formed code as plain:

``` less
@list: a;
@list: @list; // error
```

There's no way to concatenate a variable to itself (depending on the use-case usually there're more Lessish non-imperative methods to achieve the goal - for example - there're probably more related examples at SO).

**Comment by seven-phases-max** [comment] 2016-09-20 19:58
Closing as expected behaviour.

**Closed as completed by seven-phases-max** 2016-09-20 19:58 UTC
